- name: Add pip3 as pip to .zshrc
  ansible.builtin.blockinfile:
    create: true
    path: ~/.zshrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR PYTHON"
    mode: "0644"
    block: |
      alias pip=pip3
      alias python=python3

- name: Install python
  community.general.homebrew:
    name: python

- name: Install pipx
  community.general.homebrew:
    name: pipx

- name: Install vim plugin
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "~/.vim/bundle/{{ item.dest }}"
    force: true
  with_items:
    - {repo: "https://github.com/Vimjas/vim-python-pep8-indent.git", dest: vim-python-pep8-indent}
