- name: Install Codex
  ansible.builtin.shell: >
    export NVM_DIR="$HOME/.nvm" &&
    . "$(brew --prefix nvm)/nvm.sh" &&
    nvm use v22.14.0 &&
    npm install @openai/codex --global
  register: npm_install_codex
  changed_when: "'added' in npm_install_codex.stdout"
