- name: Install tap for flutter version manager
  community.general.homebrew_tap:
    name: leoafarias/fvm

- name: Install flutter version manager
  community.general.homebrew:
    name: fvm

- name: Install flutter
  ansible.builtin.command:
    cmd: fvm install 3.19.5
    creates: $HOME/fvm/versions/3.19.5

- name: Update .zshrc
  ansible.builtin.blockinfile:
    create: true
    path: ~/.zshrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR FVM"
    mode: "0644"
    block: |
      export PATH="$HOME/fvm/default/bin:$PATH"

- name: Install lcov for code coverage
  community.general.homebrew:
    name: lcov

- name: Install vim plugin
  ansible.builtin.git:
    repo: https://github.com/dart-lang/dart-vim-plugin.git
    dest: ~/.vim/bundle/dart-vim-plugin
    force: true
