- name: Install tap for flutter version manager
  community.general.homebrew_tap:
    name: leoafarias/fvm

- name: Install flutter version manager
  community.general.homebrew:
    name: fvm

- name: Install flutter
  ansible.builtin.command: fvm install 3.19.5
