- name: Install balena etcher bootable USB creator
  community.general.homebrew_cask:
    name: balenaetcher

- name: Install testdisk
  community.general.homebrew:
    name: testdisk

- name: System monitor for the menu bar
  community.general.homebrew_cask:
    name: stats

- name: Install Deskreen to use any device with a browser as an extended display
  community.general.homebrew_cask:
    name: deskreen

- name: Install BetterDisplay for display resolution, brightness and HiDPI control
  community.general.homebrew_cask:
    name: betterdisplay
