- name: Install balena etcher bootable USB creator
  community.general.homebrew_cask:
    name: balenaetcher

- name: Install testdisk
  community.general.homebrew:
    name: testdisk

- name: System monitor for the menu bar
  community.general.homebrew_cask:
    name: stats
