- name: Install llama.cpp
  community.general.homebrew:
    name: llama.cpp

- name: Install Hugging Face CLI (huggingface-cli) via pipx
  ansible.builtin.pip:
    name: huggingface_hub
    executable: pipx

- name: Install Claude Code Router
  community.general.npm:
    name: "@musistudio/claude-code-router"
    global: true
