- name: Install Visual Studio Code
  community.general.homebrew_cask:
    name: visual-studio-code

- name: Install PyCharm Community Edition
  community.general.homebrew_cask:
    name: pycharm-ce

- name: Install Devin Desktop
  community.general.homebrew_cask:
    name: devin-desktop
  when: "'devin-desktop' not in skipped_casks"

- name: Install cline for vscode/devin code generation in background
  community.general.npm:
    name: cline
    global: true
    state: present

- name: Install intellij idea Community Edition
  community.general.homebrew_cask:
    name: intellij-idea-ce

- name: Install Google's Gemini CLI
  community.general.npm:
    name: '@google/gemini-cli'
    global: true
    state: present
  tags: [ide, gemini-cli]

- name: Install OpenAI's Codex CLI
  community.general.npm:
    name: '@openai/codex'
    global: true
    state: present
  tags: [ide, codex-cli]
